---
id: chuork01
base_name: ruby-below-rails
tags:
- rabbit
- chuork01
presentation_date: 2014/02/08
version: 2014.2.8.1
licenses:
- CC BY 3.0
slideshare_id: chuork01
speaker_deck_id: 
ustream_id: 
vimeo_id: 
author:
  markup_language: :rd
  name: Masafumi Yokoyama
  email: myokoym@gmail.com
  rubygems_user: myokoym
  slideshare_user: myokoym
  speaker_deck_user: myokoym
